### ISSUE TITLE
Coercions should be explicitly imported

### ISSUE THREAD

**Issue by ppedrot** [bmsherman/topology#23]
See coq/coq#8094.

**Comment by bmsherman** [comment]
I don't have time to do this. Is it a workable solution to just drop this project from the CI test suite?

**Comment by maximedenes** [comment]
> Is it a workable solution to just drop this project from the CI test suite?

Indeed I think this is the only solution for now, as this has blocked some desirable clean-ups on the Coq side for some time already.

On the longer term, I think @Zimmi48 suggested this development could be moved to coq-community. I'll let him say more about it.

**Comment by Zimmi48** [comment]
Indeed, since, as far as I understand, this project is not actively developed anymore, it could be transferred to coq-community if it can find a new maintainer there. Have a look at the [manifesto](https://github.com/coq-community/manifesto). If you think it makes sense, you could open a new issue to advertise that this project is looking for a new maintainer.

**Comment by ppedrot** [comment]
Let's close this since it's not in the CI anymore.
